// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfcK7tPyvrFgLyX2kPYDqvABI_voWd8Cw',
    appId: '1:708129079850:web:f68a67497bec681c83b953',
    messagingSenderId: '708129079850',
    projectId: 'task1-b6b06',
    authDomain: 'task1-b6b06.firebaseapp.com',
    storageBucket: 'task1-b6b06.appspot.com',
    measurementId: 'G-R9H2YQW203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3RcEdW9wApzqBixZD_bmLi1pSKbeA04',
    appId: '1:708129079850:android:2c0a317e6a045b5683b953',
    messagingSenderId: '708129079850',
    projectId: 'task1-b6b06',
    storageBucket: 'task1-b6b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJQkrDOvtvSOBcr-GAVaq-v-iXP63ss8',
    appId: '1:708129079850:ios:1fa7e97013959d0883b953',
    messagingSenderId: '708129079850',
    projectId: 'task1-b6b06',
    storageBucket: 'task1-b6b06.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJQkrDOvtvSOBcr-GAVaq-v-iXP63ss8',
    appId: '1:708129079850:ios:3c392639efff6a1183b953',
    messagingSenderId: '708129079850',
    projectId: 'task1-b6b06',
    storageBucket: 'task1-b6b06.appspot.com',
    iosBundleId: 'com.example.task1.RunnerTests',
  );
}
